// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task.proto

package mq

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type STAGE int32

const (
	STAGE_PENDING STAGE = 0
	STAGE_SUCCESS STAGE = 1
	STAGE_FAILED  STAGE = 2
)

var STAGE_name = map[int32]string{
	0: "PENDING",
	1: "SUCCESS",
	2: "FAILED",
}

var STAGE_value = map[string]int32{
	"PENDING": 0,
	"SUCCESS": 1,
	"FAILED":  2,
}

func (x STAGE) String() string {
	return proto.EnumName(STAGE_name, int32(x))
}

func (STAGE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{0}
}

type Task struct {
	Subject              string   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Argv                 []byte   `protobuf:"bytes,3,opt,name=argv,proto3" json:"argv,omitempty"`
	Stage                STAGE    `protobuf:"varint,4,opt,name=stage,proto3,enum=mq.STAGE" json:"stage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Task) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Task) GetArgv() []byte {
	if m != nil {
		return m.Argv
	}
	return nil
}

func (m *Task) GetStage() STAGE {
	if m != nil {
		return m.Stage
	}
	return STAGE_PENDING
}

func init() {
	proto.RegisterEnum("mq.STAGE", STAGE_name, STAGE_value)
	proto.RegisterType((*Task)(nil), "mq.Task")
}

func init() { proto.RegisterFile("task.proto", fileDescriptor_ce5d8dd45b4a91ff) }

var fileDescriptor_ce5d8dd45b4a91ff = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2c, 0xce,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xca, 0x2d, 0x54, 0x4a, 0xe5, 0x62, 0x09, 0x49,
	0x2c, 0xce, 0x16, 0x92, 0xe0, 0x62, 0x2f, 0x2e, 0x4d, 0xca, 0x4a, 0x4d, 0x2e, 0x91, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x98, 0xc0, 0x82,
	0x4c, 0x99, 0x29, 0x42, 0x42, 0x5c, 0x2c, 0x89, 0x45, 0xe9, 0x65, 0x12, 0xcc, 0x0a, 0x8c, 0x1a,
	0x3c, 0x41, 0x60, 0xb6, 0x90, 0x3c, 0x17, 0x6b, 0x71, 0x49, 0x62, 0x7a, 0xaa, 0x04, 0x8b, 0x02,
	0xa3, 0x06, 0x9f, 0x11, 0xa7, 0x5e, 0x6e, 0xa1, 0x5e, 0x70, 0x88, 0xa3, 0xbb, 0x6b, 0x10, 0x44,
	0x5c, 0x4b, 0x97, 0x8b, 0x15, 0xcc, 0x17, 0xe2, 0xe6, 0x62, 0x0f, 0x70, 0xf5, 0x73, 0xf1, 0xf4,
	0x73, 0x17, 0x60, 0x00, 0x71, 0x82, 0x43, 0x9d, 0x9d, 0x5d, 0x83, 0x83, 0x05, 0x18, 0x85, 0xb8,
	0xb8, 0xd8, 0xdc, 0x1c, 0x3d, 0x7d, 0x5c, 0x5d, 0x04, 0x98, 0x92, 0xd8, 0xc0, 0x0e, 0x34, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x58, 0x1f, 0x32, 0x14, 0xae, 0x00, 0x00, 0x00,
}
